[tool.pytest.ini_options]
filterwarnings = [
    "ignore:module 'sre_constants' :DeprecationWarning",
    'ignore:The distutils\.sysconfig module:DeprecationWarning',
    "ignore:The distutils package :DeprecationWarning",
    "ignore:the imp module :DeprecationWarning",
]

[tool.ruff.lint]
extend-select = ["D"]
ignore = ["D105", "D203", "D212"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
